### PR TITLE
Hide Keyboard

### PR DESCRIPTION
**Pull request by MuhammadImran2**
When I open app it show keyboard like 
signal-2021-07-14-222921
Solve this issue

### CODE REVIEW

**Comment by MuhammadImran2** [comment]
night

and when I turn on and off Night Mode the keyboard appear

**Comment by MuhammadImran2** [comment]
Sir No responsee From you

**Comment by bkhezry** [comment]
Sorry for the delay.

**Comment by MuhammadImran2** [comment]
ok

**Comment by MuhammadImran2** [comment]
ok

**Comment by MuhammadImran2** [comment]
Thank you @bkhezry  for merged my commit :heart:

**Pull request merged**
